/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskmanagementsystem;


/**
 *
 * @author user
 */
public class TaskManagementSystemAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TaskManagementSystemAdmin
     */
    public TaskManagementSystemAdmin() {
        initComponents();
          pnlCreatAccount.setVisible(false);
          pnlAddTask.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminDashbord = new javax.swing.JPanel();
        lblWelcom = new javax.swing.JLabel();
        btnCreatAccount = new javax.swing.JButton();
        pnlCreatAccount = new javax.swing.JPanel();
        lblUserName = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        btnCreat = new javax.swing.JButton();
        btnAddTask = new javax.swing.JButton();
        pnlAddTask = new javax.swing.JPanel();
        lblTaskName = new javax.swing.JLabel();
        txtTaskName = new javax.swing.JTextField();
        lblIDTask = new javax.swing.JLabel();
        txtIDTask = new javax.swing.JTextField();
        lblDeadLine = new javax.swing.JLabel();
        txtFormatDeadLine = new javax.swing.JFormattedTextField();
        btnSaveTask = new javax.swing.JButton();
        btnManageTask = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnEmployee = new javax.swing.JButton();
        pnlManTask = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdminEdit = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlAdminDashbord.setBorder(javax.swing.BorderFactory.createTitledBorder("Admin Dashboard"));

        lblWelcom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblWelcom.setText("Welcome , Admin");

        btnCreatAccount.setText("Create Employee Account");
        btnCreatAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatAccountActionPerformed(evt);
            }
        });

        lblUserName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUserName.setText("UserName");

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setText("Password");

        txtPassword.setToolTipText("");

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setText("ID");

        btnCreat.setText("Create");
        btnCreat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreatAccountLayout = new javax.swing.GroupLayout(pnlCreatAccount);
        pnlCreatAccount.setLayout(pnlCreatAccountLayout);
        pnlCreatAccountLayout.setHorizontalGroup(
            pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatAccountLayout.createSequentialGroup()
                .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreatAccountLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUserName)
                            .addComponent(lblPassword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPassword)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCreatAccountLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(lblID))
                    .addGroup(pnlCreatAccountLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(btnCreat)))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pnlCreatAccountLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtPassword, txtUserName});

        pnlCreatAccountLayout.setVerticalGroup(
            pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreatAccountLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(pnlCreatAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnCreat)
                .addGap(33, 33, 33))
        );

        btnAddTask.setText("Add Task");
        btnAddTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTaskActionPerformed(evt);
            }
        });

        lblTaskName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTaskName.setText("Task Name");

        lblIDTask.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIDTask.setText("ID");

        lblDeadLine.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDeadLine.setText("Deadline");

        txtFormatDeadLine.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.FULL))));

        btnSaveTask.setText("Save Task");
        btnSaveTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAddTaskLayout = new javax.swing.GroupLayout(pnlAddTask);
        pnlAddTask.setLayout(pnlAddTaskLayout);
        pnlAddTaskLayout.setHorizontalGroup(
            pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddTaskLayout.createSequentialGroup()
                .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddTaskLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(lblDeadLine)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtFormatDeadLine))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAddTaskLayout.createSequentialGroup()
                        .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlAddTaskLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(lblTaskName))
                            .addGroup(pnlAddTaskLayout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(lblIDTask)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTaskName)
                            .addComponent(txtIDTask))))
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAddTaskLayout.createSequentialGroup()
                .addGap(0, 156, Short.MAX_VALUE)
                .addComponent(btnSaveTask)
                .addGap(115, 115, 115))
        );
        pnlAddTaskLayout.setVerticalGroup(
            pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddTaskLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTaskName)
                    .addComponent(txtTaskName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDTask)
                    .addComponent(txtIDTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(pnlAddTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeadLine)
                    .addComponent(txtFormatDeadLine, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnSaveTask)
                .addGap(33, 33, 33))
        );

        btnManageTask.setText("Manage Task");

        btnReport.setText("Report Page");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnEmployee.setText("Employee Page");
        btnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeActionPerformed(evt);
            }
        });

        pnlManTask.setBorder(javax.swing.BorderFactory.createTitledBorder("Table Task"));

        tableAdminEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Task", "Employee", "Status", "Deadline", "Action"
            }
        ));
        jScrollPane1.setViewportView(tableAdminEdit);

        javax.swing.GroupLayout pnlManTaskLayout = new javax.swing.GroupLayout(pnlManTask);
        pnlManTask.setLayout(pnlManTaskLayout);
        pnlManTaskLayout.setHorizontalGroup(
            pnlManTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlManTaskLayout.setVerticalGroup(
            pnlManTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlManTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdminDashbordLayout = new javax.swing.GroupLayout(pnlAdminDashbord);
        pnlAdminDashbord.setLayout(pnlAdminDashbordLayout);
        pnlAdminDashbordLayout.setHorizontalGroup(
            pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminDashbordLayout.createSequentialGroup()
                .addGroup(pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btnCreatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblWelcom)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminDashbordLayout.createSequentialGroup()
                .addComponent(pnlCreatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(btnManageTask, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlManTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReport)
                    .addComponent(btnEmployee))
                .addGap(71, 71, 71))
        );

        pnlAdminDashbordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAddTask, btnCreatAccount});

        pnlAdminDashbordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEmployee, btnReport});

        pnlAdminDashbordLayout.setVerticalGroup(
            pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblWelcom)
                .addGap(26, 26, 26)
                .addGroup(pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatAccount)
                    .addComponent(btnAddTask))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlAddTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlCreatAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(btnManageTask)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminDashbordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminDashbordLayout.createSequentialGroup()
                        .addComponent(btnReport)
                        .addGap(46, 46, 46)
                        .addComponent(btnEmployee))
                    .addComponent(pnlManTask, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAdminDashbordLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {pnlAddTask, pnlCreatAccount});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminDashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminDashbord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
              TaskManagementSystemReports Reports=new TaskManagementSystemReports();
              Reports.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeActionPerformed
               EmployeeTaskManegmentEmployeeInfo Employee=new EmployeeTaskManegmentEmployeeInfo() ;
              Employee.setVisible(true);
              this.setVisible(false);
    }//GEN-LAST:event_btnEmployeeActionPerformed

    private void btnCreatAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatAccountActionPerformed
        // TODO add your handling code here:
         pnlCreatAccount.setVisible(true);
       
    }//GEN-LAST:event_btnCreatAccountActionPerformed

    private void btnAddTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTaskActionPerformed
        // TODO add your handling code here:
           pnlAddTask.setVisible(true);
          
    }//GEN-LAST:event_btnAddTaskActionPerformed

    private void btnCreatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatActionPerformed
       ValidationUtil.isEmpty(txtUserName);
       ValidationUtil.isEmpty(txtPassword);
       ValidationUtil.isValidLength(txtID, 10);
    }//GEN-LAST:event_btnCreatActionPerformed

    private void btnSaveTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveTaskActionPerformed
        // TODO add your handling code here:
        ValidationUtil.isValidLength(txtIDTask,10);
        ValidationUtil.isEmpty(txtFormatDeadLine);
        ValidationUtil.isEmpty(txtTaskName);
    }//GEN-LAST:event_btnSaveTaskActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskManagementSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskManagementSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskManagementSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
               } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskManagementSystemAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaskManagementSystemAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTask;
    private javax.swing.JButton btnCreat;
    private javax.swing.JButton btnCreatAccount;
    private javax.swing.JButton btnEmployee;
    private javax.swing.JButton btnManageTask;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSaveTask;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDeadLine;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDTask;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTaskName;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblWelcom;
    private javax.swing.JPanel pnlAddTask;
    private javax.swing.JPanel pnlAdminDashbord;
    private javax.swing.JPanel pnlCreatAccount;
    private javax.swing.JPanel pnlManTask;
    private javax.swing.JTable tableAdminEdit;
    private javax.swing.JFormattedTextField txtFormatDeadLine;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtIDTask;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtTaskName;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
